---
development:
  cloud_name: db3kljtw9
  api_key: "932935994286465"
  api_secret: wyze4QdaUwsDzzXNjXkiClskBbs
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: db3kljtw9
  api_key: "932935994286465"
  api_secret: wyze4QdaUwsDzzXNjXkiClskBbs
  enhance_image_tag: true
  static_file_support: true

test:
  cloud_name: db3kljtw9
  api_key: "932935994286465"
  api_secret: wyze4QdaUwsDzzXNjXkiClskBbs
  enhance_image_tag: true
  static_file_support: false
